### ISSUE TITLE
Add test for bin/licenser

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/licenser#34]
This unit test should verify the correct options for the licenser as there are no test for this at the moment.

**Comment by helio-frota** [comment]
So I'm going to close this.
After look the code on 20+ yargs [dependents](https://www.npmjs.com/browse/depended/yargs), all follow the same approach
to test only the /lib/foo or /api/foo not the bin/foo, I mean since nothing is exported on /bin/licenser
and the data is passed/delegated to another source code inside /lib/foo to handle.

we can reopen in a future when we find solution or approach found for this, but I think we are doing the good for now.
