### ISSUE TITLE
Support a warning when a dependency has an unknown license

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/licenser#7]
The license generation process should complete when triggered, but if there is any license indicated as UNKNOWN or a dependency hasn't got a license which exists on a RH whitelist, then a WARNING should be displayed to the user on license generation completion.

**Comment by lgriffin** [comment]
I wonder should the license type and associated data also state Unknown instead of MIT / Apache etc. I'm assuming a wider tool or a variant of our tool will be scanning for such instances as an Unknown license generally means we need to contact someone legally to figure it out!

Similarly for warning, but in that case we probably want the license type so we can action it. We have a lot of flexibility in the "header" of the XML file where we state the product specific metadata such as version, name, contact details etc. We might add an <infractions> tag.

WDYT?

**Comment by danbev** [comment]
Not sure I'm following you exactly here Leigh, can we have a quick chat tomorrow and iron this out?

**Comment by lgriffin** [comment]
Sure thing Dan, just ping me!

**Comment by danbev** [comment]
To clarify this (for myself at least) when we find a license that is not in the whitelist then it should be listed as unknown. There will be a warning produced which specifies the type of licenses that were not in the whitelist:
```console
========= WARNING NON WHITE-LISTED LICENSES ==========
name: js2xmlparser , version: 3.0.0 , license: Apache-2.0
name: license-checker , version: 11.0.0 , license: BSD-3-Clause
========= WARNING NON WHITE-LISTED LICENSES ==========
```

So this task should perform the whitelist check and mark any non listed licenses as unknown in the generated xml, in addition to the generated warning.
@lgriffin Could you confirm that I've understood this correctly?

**Comment by lgriffin** [comment]
My understanding here is that we have almost 3 valid states around 4 use cases.  We only need to report on two of those states, WARNING and UNKNOWN. Let me give you the scenarios and the context and my own thoughts on it.

1. The license is in our whitelist, it's valid yay! Technically we don't list this state, but let's call it VALID for our purposes here. 99% of our licenses should fall here to be fair.

2. The license is not in our whitelist, it *might* be valid, it *might not* be valid that's not up to us to guess. We should print a warning. WARNING is our state here

3. The license cannot be inferred because the package.json and other metadata sources are not telling us what we need to know. UNKNOWN is our state here.

4. The license appears in our bad licenses list / blacklist / non-white list. WARNING is our state here but this is a much more serious warning

Additional context for each scenario:

1. No action, we are all good!

2. If the license is not in a whitelist it's license is listed BUT it is flagged as a Warning with something to indicate that the license type is "not in whitelist". It could be a case that the there is an exemption and somebody forgot to update the whitelist OR it could be a case that it's a new license type that we never heard of. This is typically an action here on legal or on an Engineering Manager to figure this out.

3. If the license has no associated license metadata it's a huge security concern. It is listed as an UNKNOWN. That's much more worrying and would require immediate action by someone. So hierarchically, this would come above a warning in the ordering. We shouldn't be publishing or working with dependencies that have no way for us to infer their license type. 

4. If we have a 2nd list to identify licenses we don't want to work with AND a license appears in there. We need to flag it as a WARNING and let someone (legal / manager) decide whether this is ok and gain an exemption. At which point that license should be moved out of the 2nd list and into the white list, thus making it valid for this particular product.

**Comment by danbev** [comment]
Thanks @lgriffin. 

So what we are missing currently is the reporting of an unknown license, one that does not have a license file but could possibly have a license "type" that is in the whitelist. If it is not in the whitelist it will be reported in that section as well. 

Then an example of all warnings would be something like
```console
========= WARNING NON WHITE-LISTED LICENSES ==========
name: js2xmlparser , version: 3.0.0 , license: Apache-2.0
name: license-checker , version: 11.0.0 , license: BSD-3-Clause
========= WARNING NON WHITE-LISTED LICENSES ==========

========= WARNING UNKNOWN LICENSES ==========
name: js2xmlparser , version: 3.0.0 , license: Unknown
name: license-checker , version: 11.0.0 , license: Unknown
========= WARNING UNKNOWN LICENSES ==========

========= WARNING BLACK-LISTED LICENSES ==========
name: js2xmlparser , version: 3.0.0 , license: Apache-2.0
name: license-checker , version: 11.0.0 , license: BSD-3-Clause
========= WARNING BLACK-LISTED LICENSES ==========
```


The blacklist will be handled by a separate issue (#35)

**Comment by lgriffin** [comment]
That reporting structure looks perfect Dan 👍 
Just to clarify something we spoke about as well (for others looking in!):
We have freedom for how best to represent this in the XML structure to put an attribute that flags it somehow.  Further down the line some tool will be parsing this XML so while the logging / reporting is great to have, a more persistent flag needs to be in the XML.
